export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';

export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL';
export const SET_ROLE = 'SET_ROLE';

export const GET_EMPLOYEES_REQUEST = 'GET_EMPLOYEES_REQUEST';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_FAIL = 'GET_EMPLOYEES_FAIL';


export const SET_FILE = 'SET_FILE';


export const SEARCH_EMPLOYEE = 'SEARCH_EMPLOYEE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

export const GET_CREATOR_TASKS = "GET_CREATOR_TASKS"
export const GET_EXECUTOR_TASKS = "GET_EXECUTOR_TASKS"

export const SAVE_TASK_REQUEST = "SAVE_TASK_REQUEST"
export const SAVE_TASK_SUCCESS = "SAVE_TASK_SUCCESS"
export const SAVE_TASK_ERROR = "SAVE_TASK_ERROR"
export const CONFIRM_SAVE_INFO = "CONFIRM_SAVE_INFO"

export const SET_EDIT_TASK = "SET_EDIT_TASK"
export const DELETE_TASK = "DELETE_TASK"

export const FILTER_TASKS = "FILTER_TASKS"
export const FILTER_TASKS_BY_EXECUTOR = "FILTER_TASKS_BY_EXECUTOR"
export const FILTER_TASKS_BY_TITLE = "FILTER_TASKS_BY_TITLE"

export const FILTER_EXECUTOR_TASKS = "FILTER_EXECUTOR_TASKS"

export const CREATE_OLD_EXECUTOR_LIST = "CREATE_OLD_EXECUTOR_LIST"
export const CLEAN_EXECUTOR_LIST = "CLEAN_EXECUTOR_LIST"


export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_SUB_CATEGORIES = 'GET_SUB_CATEGORIES'
export const GET_VARIABLES = 'GET_VARIABLES'
export const SET_TYPE = 'SET_TYPE'
export const CREATE_NEW_VAR_RADIO = 'CREATE_NEW_VAR_RADIO'
export const DELETE_VAR_RADIO = 'DELETE_VAR_RADIO'
export const SET_VAR_CREATE_MESSAGE_SUCCESS = 'SET_VAR_CREATE_MESSAGE_SUCCESS'
export const SET_VAR_CREATE_MESSAGE_FAIL = 'SET_VAR_CREATE_MESSAGE_FAIL'

export const CLOSE_POPUP = 'CLOSE_POPUP'

export const DELETE_VARIABLE = 'DELETE_VARIABLE'
export const OPEN_DELETE_POPUP = 'OPEN_DELETE_POPUP'
export const CLOSE_DELETE_POPUP = 'CLOSE_DELETE_POPUP'
export const CLEAR_RADIO_VAR_LIST = 'CLEAR_RADIO_VAR_LIST'
export const GET_VAR_BY_ID = 'GET_VAR_BY_ID'
export const SET_VARS_FOR_EDIT = 'SET_VARS_FOR_EDIT'
export const EDIT_VAR_ACTION_SUCCESS = 'EDIT_VAR_ACTION_SUCCESS'
export const EDIT_VAR_ACTION_ERROR = 'EDIT_VAR_ACTION_ERROR'
export const CLOSE_EDIT_POPUP = 'CLOSE_EDIT_POPUP'
export const CREATE_DOC_REQUEST = 'CREATE_DOC_REQUEST'
export const CREATE_DOC_SUCCESS = 'CREATE_DOC_SUCCESS'
export const CREATE_DOC_ERROR = 'CREATE_DOC_ERROR'
export const SEARCH_VAR = 'SEARCH_VAR'
export const ADD_VAR_TO_LIST = 'ADD_VAR_TO_LIST'
export const DELETE_ADDED_VAR = 'DELETE_ADDED_VAR'
// export const SET_FILE = 'SET_FILE'

export const OPEN_DOC_POPUP_SUCCESS = 'OPEN_DOC_POPUP_SUCCESS'
export const OPEN_DOC_POPUP_ERROR = 'OPEN_DOC_POPUP_ERROR'
export const CLOSE_DOC_POPUP = 'CLOSE_DOC_POPUP'
export const CLEAR_ADDED_VARS_ACTION = 'CLEAR_ADDED_VARS_ACTION'
export const CREATE_CAT = 'CREATE_CAT'
export const CLOSE_DELETE_CAT_POPUP = 'CLOSE_DELETE_CAT_POPUP'

export const OPEN_CAT_POPUP_SUCCESS = 'OPEN_CAT_POPUP_SUCCESS'
export const OPEN_CAT_POPUP_ERROR = 'OPEN_CAT_POPUP_ERROR'
export const CLOSE_CAT_POPUP = 'CLOSE_CAT_POPUP'
export const GET_TEMPLATE_DATA = 'GET_TEMPLATE_DATA'
export const SET_CURRENT_CATEGORY_NAME = 'SET_CURRENT_CATEGORY_NAME'
export const SET_TEMPLATE_TO_CREATE = 'SET_TEMPLATE_TO_CREATE'
export const CREATE_DOC_FROM_TEMPLATE_SUCCESS = 'CREATE_DOC_FROM_TEMPLATE_SUCCESS'
export const CREATE_DOC_FROM_TEMPLATE_ERROR = 'CREATE_DOC_FROM_TEMPLATE_ERROR'
export const CLOSE_CREATE_DOC_FROM_TEMPLATE_ERROR = 'CLOSE_CREATE_DOC_FROM_TEMPLATE_ERROR'
export const SET_SUBCAT_LIST = 'SET_SUBCAT_LIST'
export const SET_TEMPLATES = 'SET_TEMPLATES'
export const CHANGE_EDIT_POPUP = 'CHANGE_EDIT_POPUP'
export const OPEN_DELETE_CAT_POPUP = 'OPEN_DELETE_CAT_POPUP'
export const OPEN_EDIT_CAT_POPUP = 'OPEN_EDIT_CAT_POPUP'
export const DELETE_CAT = 'DELETE_CAT'
export const CLOSE_EDIT_CAT_POPUP = 'CLOSE_EDIT_CAT_POPUP'
export const SET_TEMPLATE_TO_EDIT = 'SET_TEMPLATE_TO_EDIT'
export const DELETE_ADDED_VAR_IN_EDIT = 'DELETE_ADDED_VAR_IN_EDIT'
export const DELETE_FILE = 'DELETE_FILE'

